# Translations template for cinder.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the cinder project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Cinder\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-11-11 06:09+0000\n"
"PO-Revision-Date: 2014-11-10 13:52+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Chinese (China) (http://www.transifex.com/projects/p/cinder/"
"language/zh_CN/)\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: cinder/backup/manager.py:445
msgid "Failed to update usages deleting backup"
msgstr ""

#: cinder/backup/manager.py:629
msgid "Backup driver has not been initialized"
msgstr ""

#: cinder/backup/drivers/ceph.py:459
#, python-format
msgid ""
"Max retries reached deleting backup %(basename)s image of volume %(volume)s."
msgstr ""

#: cinder/backup/drivers/ceph.py:495
#, python-format
msgid "Pipe1 failed - %s "
msgstr ""

#: cinder/backup/drivers/ceph.py:509
#, python-format
msgid "Pipe2 failed - %s "
msgstr ""

#: cinder/backup/drivers/ceph.py:973
msgid "Differential restore failed, trying full restore"
msgstr ""

#: cinder/backup/drivers/ceph.py:1175
#, python-format
msgid "Restore to volume %(volume)s finished with error - %(error)s."
msgstr ""

#: cinder/backup/drivers/swift.py:159
#, python-format
msgid "single_user auth mode enabled, but %(param)s not set"
msgstr ""

#: cinder/backup/drivers/swift.py:394
#, python-format
msgid "Backup volume metadata to swift failed: %s"
msgstr ""

#: cinder/backup/drivers/tsm.py:252
#, python-format
msgid ""
"backup: %(vol_id)s failed to remove backup hardlink from %(vpath)s to "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""

#: cinder/backup/drivers/tsm.py:531
#, python-format
msgid ""
"delete: %(vol_id)s failed with stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:50
#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:75
#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:106
#, python-format
msgid "Table |%s| not created!"
msgstr "表 |%s| 没有创建"

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:128
msgid "Dropping foreign key reservations_ibfk_1 failed."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:134
msgid "quota_classes table not dropped"
msgstr "未删除 quota_classes 表"

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:141
msgid "quota_usages table not dropped"
msgstr "未删除 quota_usages 表"

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:148
msgid "reservations table not dropped"
msgstr "未删除预留表"

#: cinder/db/sqlalchemy/migrate_repo/versions/015_drop_migrations_table.py:32
msgid "migrations table not dropped"
msgstr "未删除 migrations 表"

#: cinder/db/sqlalchemy/migrate_repo/versions/015_drop_migrations_table.py:62
#, python-format
msgid "Table |%s| not created"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/021_add_default_quota_class.py:76
msgid "Default quota class data not inserted into the DB."
msgstr ""

#: cinder/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "正在删除原始异常：%s"

#: cinder/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "意外的异常已发生 %d 次...正在重试。"

#: cinder/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "在固定时段内循环调用"

#: cinder/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "在动态循环调用中"

#: cinder/openstack/common/periodic_task.py:202
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr "在 %(full_task_name)s 期间发生错误：%(e)s"

#: cinder/openstack/common/policy.py:508
#, python-format
msgid "Failed to understand rule %s"
msgstr "未能理解规则 %s"

#: cinder/openstack/common/policy.py:518
#, python-format
msgid "No handler for matches of kind %s"
msgstr "对于类型为 %s 的匹配项，不存在任何处理程序"

#: cinder/openstack/common/policy.py:788
#, python-format
msgid "Failed to understand rule %r"
msgstr "未能理解规则 %r "

#: cinder/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "在RPC清除期间发生异常。"

#: cinder/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "存在未处理的异常"
